services:
  php:
    container_name: reservations-api-php
    build:
      context: ./docker/php8.3
    volumes:
      - ./:/var/www/html
      - ./docker/php8.3/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php8.3/php.ini:/usr/local/etc/php/php.ini
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CLIENT_HOST: host.docker.internal
    ports:
      - "9000:9090"
    depends_on:
      - mysql

  mysql:
    container_name: reservations-api-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    container_name: reservations-api-nginx
    image: nginx:latest
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

volumes:
  db_data:
